### ISSUE TITLE
Enable stopping jobs during container provisioning

### ISSUE THREAD

**Issue by emgrasmeder** [bob-cd/bob#100]
While working on #98, I came across the issue that jobs cannot be stopped while they're in the container provison phase of the run. This will especially be a problem for runners that are trying to use images which take hours to download. I don't want to wait 6 hours for a huge image to finish downloading before I can stop it.

**Comment by lispyclouds** [comment]
Implemented in https://github.com/bob-cd/bob/commit/95b14bcd493afe2d9d58d8a660b42acff3f76f1a
cc @emgrasmeder

**Comment by emgrasmeder** [comment]
I'd like to keep this open til I get the e2e test (the one that made us rasie this this issue) passing.
