### ISSUE TITLE
Add status when pipeline cannot be paused

### ISSUE THREAD

**Issue by emgrasmeder** [bob-cd/bob#102]
During provisioning / initialization of a pipeline(e.g. downloading an image), the pipeline cannot be paused. We should notify users that the pipeline cannot be paused, so they know to either stop the pipeline or retry pausing later. 

A suggestion for the return status could be: `unpausable/provisioning`. The status code would be 422. 

The actual internal state of bob should have the pipeline status listed as :initializing until the image pull is complete, after which it can be :running

**Comment by lispyclouds** [comment]
Implemented in https://github.com/bob-cd/bob/commit/51152c80ab54230766be9968da3ccd953838c6dd
cc @emgrasmeder
