### ISSUE TITLE
Record the timestamp of pipeline status changes

### ISSUE THREAD

**Issue by emgrasmeder** [bob-cd/bob#105]
As a pipeline status moves from `initializing` to `running` to `completed` or `failed` etc., the timestamp of the change should be recorded so that we can fetch them from the /metrics endpoint

**Comment by aldosolorzano** [comment]
Hi, I've recently discovered Bob and I'm quite fascinated by it. I would like to contribute with something, so I started with the `good first issues` 
Regarding this one, those this [timestamp](https://github.com/bob-cd/bob/blob/main/runner/src/runner/pipeline.clj#L231) in the pipeline covers the intention of this issue? If so, maybe we should move to completed the issue.

**Comment by lispyclouds** [comment]
Thanks for the interest @aldosolorzano! Super happy that you'd like to contribute!

As for this, the timestamp you found _sort of_ covers this but the intention of this was to be more granular. The pipeline currently has [these](https://github.com/bob-cd/bob/blob/main/common/src/common/schemas.clj#L91) states and we'd like to note the times when it switched between them. This was more from the perspective of having a historical log and metrics standpoint.

Hope this helps and please do let us know if we can provide more info and feedback at any levels is most welcome!

**Comment by aldosolorzano** [comment]
I realized I shared the wrong line, I mean this [one](https://github.com/bob-cd/bob/blob/main/runner/src/runner/pipeline.clj#L229)  

Let me see If I understood correctly the intention. So if it transitions from `initializing` to `running` we might want to have something like `running-at`? similar to the other transitions: `failed-at` `passed-at` `stopped-at`. This will answer questions like, at what time does the pipeline transitioned to failure or passed, calculate how much time was spent in each status, the historical log of the transitions etc... Does this goes with what you are trying to achieve?

**Comment by lispyclouds** [comment]
Yes, that's the intention pretty much! Apart from the specific keys for the timestamps, we could also make use of the fact that we have XT which is temporal so we can use the history of the pipeline like [this](https://docs.xtdb.com/language-reference/datalog-queries/#history-full-document-history). This essentially would get rid of timestamps in general. We have to modify the code a bit to have valid times, as in explicitly pass an Instant when putting the changes to XT. What do you think?

**Comment by aldosolorzano** [comment]
This sounds interesting, I have a couple of questions. 
1. What I understood from their docs we can fetch the history but we don't actually know what were the changes, right? we can't not guarantee that the status was the thing that changed between versions unless we compare them?
2. xtdb doesn't look complicated to work with the history features, so it could be a good approach, what I'm still not sure is about getting rid of timestamps, there are some of them that we might want to have handy (e.g the existing :completed), probably it's something that it's going to be consumed frequently from the API, soo having it handy is a good way to not deal with the history api in xtdb and adapted to a more comprehensible domain.

**Comment by lispyclouds** [comment]
Yeah sounds good. For a start lets go with `assoc`ing `:initialized :started :stopped` keys into the run with the the current timestamps and saving to XT. The existing `:completed` key should handle the case for passed and failed.

**Comment by aldosolorzano** [comment]
Cool, I'll work with that and send a PR for review. Thank you for the help

**Comment by lispyclouds** [comment]
I realise that there wasn't a dev guide, I put together some steps that have worked out: https://github.com/bob-cd/bob/blob/main/doc/dev.md
Hope that helps and feedback welcome!

**Comment by aldosolorzano** [comment]
Hi @lispyclouds I'm trying tu check my changes and from what I understand I need to run the `runner` separate from the other services. I'm trying this but I get an error

on root level of bob
```
docker compose up storage queue artifact resource apiserve
```
The services run successfully and then I try to run the `runner` on root level of `bob/runner`
```
clojure -J--enable-preview -M -m runner.main
```
and this is the error I get
```
Syntax error (NoSuchFieldException) compiling . at (runner/main.clj:27:33).
newVirtualThreadPerTaskExecutor

Full report at:
/tmp/clojure-13535403313027409658.ed
```

**Comment by lispyclouds** [comment]
Probably your java version is < 19? Bob uses virtual threads extensively, that's the min version.

**Comment by aldosolorzano** [comment]
Got it running, now when trying to start a pipeline I see `Pipeline failure: Failed to connect to localhost/0.0.0.0:8080` 
What is it suppose to run in that port?

**Comment by lispyclouds** [comment]
How do you get this error? Can you paste the pipeline spec youre running? Also are there resource providers and artifact stores involved?

**Comment by aldosolorzano** [comment]
Here it goes,
```
cat pipeline.json | http POST http://localhost:7777/pipelines/groups/dev/names/pipeline5

;; Result

{
    "message": "Ok"
}

```

It seems that it works but when I do a `get` to `/pipelines` I doesn't show up there. Then I try to start the pipeline by running 
```
http POST http://localhost:7777/pipelines/start/groups/dev/names/pipeline1
```
but it it fails with this error(NOT the localhost one i sent) 
```
Pipeline failure: Invalid pipeline in DB: 
```

The resource providers and artifact strores are the default ones, my guess is that the connection with the db is failing. When I run everything with docker compose up, it works

**Comment by lispyclouds** [comment]
ah i think, you may have the old docker images. we recently dropped the need for a service that created things and its done by the apiserver itself. try pulling the latest docker images or clear the ones you have and pull again.

**Comment by aldosolorzano** [comment]
Anyways, the changes seemed to worked. We can see the initialized timestamp and then the completed and the status is failed because of the errors I have above. 
I'm wondering If i need to add tests for this, I see handler tests and they check what is returned based on the persisted values in the db, which makes sense. The problem I see is if an external source depends on the :initialized param in the API and we remove it, it will break the integration correct?
```json
{
    "message": [
        {
            "completed": "2023-03-17T22:53:30.460047057Z",
            "initialized": "2023-03-17T22:53:30.218225301Z", 
            "run_id": "r-af19dcae-f7d4-49ef-93ba-be3f463dee77",
            "status": "failed"
        },
        {
            "completed": "2023-03-17T22:54:10.689630914Z",
            "initialized": "2023-03-17T22:54:10.587235589Z",
            "run_id": "r-10359304-7f88-4fb7-bf9c-16e5fe9acb48",
            "status": "failed"
        }
    ]
}
```

**Comment by aldosolorzano** [comment]
Side question: what do you think about a namespace that contains the db functions? I believe it can help to cleanup visually the code a little bit and improve the readability as well.  

The trade-off could be that we might hide what's happening exactly but maybe it's not needed to show at that level of the code, you might just need to know what it does, not how.
example 

```clojure
;; before

  (f/try-all [result (xt/q (xt/db db)
                           '{:find [(pull artifact-store [:name :url])]
                             :where [[artifact-store :type :artifact-store]]})]
    (respond (map first result) 200)
    (f/when-failed [err]
      (respond (f/message err) 500)))

;; after

  (f/try-all [result (db.artifact-store/pull (xt/db))] ;; It could receive some params as well, this is a very basic form
    (respond (map first result) 200)
    (f/when-failed [err]
      (respond (f/message err) 500)))

**Comment by lispyclouds** [comment]
I see the issue now.

> now we are back on the error for the localhost8080

I've added this [section](https://github.com/bob-cd/bob/blob/main/doc/dev.md#running-the-runner) to the dev docs. Hope that makes it a bit better. I'm thinking of improving the error message. The source of the issue is [here](https://github.com/bob-cd/bob/blob/main/runner/src/runner/engine.clj#L19).

> I'm wondering If i need to add tests for this

Yes tests would be good for this. You can assert the final state for the presence of the keys in a similar way the current tests are. When in doubt, raise the PR and we both can take a look! 😄 

> what do you think about a namespace that contains the db functions?

Looks like a great refactor to have and agreed on the rationale. Ideally it would be good to do it on a separate PR. Please create an issue for this and we can track it!

**Comment by lispyclouds** [comment]
Done on #122
