### ISSUE TITLE
Add get started guide for contributors

### ISSUE THREAD

**Issue by amexboy** [bob-cd/bob#111]
Trying to contribute, I noticed there is a lack of [discoverable] getting started guide. Add the tools used and state first commands to allow beginners (such as me) a smoother start.

**Comment by amexboy** [comment]
I can work on it! 

I have so far discovered that we need 

clojure binary (kind of obvious)
docker or podman
babashka https://github.com/babashka/babashka

Add examples for
- Running tests
- Building and running the compose file 


What else?

**Comment by lispyclouds** [comment]
Hey hey @amexboy! Long time! How's things? 😄 Great to have you back!

This is a great and quite needed idea and thanks for raising it. So we have the website for bob at https://github.com/bob-cd/bob-cd.github.io and I think having a proper developers section there with these info would be nicer. You could create a new section like the ones [here](https://github.com/bob-cd/bob-cd.github.io/tree/main/pages), call it `Developer's Guide` maybe?

I've tried documenting the requirements in the READMEs of dirs of the services:
- [apiserver](https://github.com/bob-cd/bob/tree/main/apiserver)
- [entities](https://github.com/bob-cd/bob/tree/main/entities)
- [runner](https://github.com/bob-cd/bob/tree/main/runner)

Babashka is used for orchestrating the monorepo. The bb commands for the services can be found in their respective dirs but for the global ones I think looking at the [CircleCI](https://github.com/bob-cd/bob/blob/main/.circleci/config.yml) steps would be useful.

Bob can run either in Docker or Podman, would be great if we can document it for both! See the depoly [repo](https://github.com/bob-cd/bob-deploy) for more details.

See if they are enough? Let me know if you have enough info to get started on the dev guide, more than happy to help wherever needed!

**Comment by lispyclouds** [comment]
Once we have that, maybe we can think of having a more detailed and code level guide too! 😄

**Comment by amexboy** [comment]
@lispyclouds I am really glad to see the project is still going. 

I will get started on this.

Thank you for the tips, very useful. The codebase changed quite a bit, I will document my journey while discovering the new world order.

**Comment by amexboy** [comment]
> Once we have that, maybe we can think of having a more detailed and code level guide too! smile

Yes we can! 🔨 🔨

**Comment by lispyclouds** [comment]
Thanks a lot! Excited to see the outcome! 😄 

> The codebase changed quite a bit

yeah had a LOT of hammock time in the middle, loads of WTFs, but I think this is in a shape I'd like to be in. quite a journey.

**Comment by lispyclouds** [comment]
Here is a start: https://github.com/bob-cd/bob/blob/main/doc/dev.md
