### ISSUE TITLE
Allow testing specific ns

### ISSUE THREAD

**Issue by aldosolorzano** [bob-cd/bob#123]
While developing I wanted to only test the ns relevant to my changes in the `runner` and `bb test` always ran the whole thing. I added `(apply shell "clojure -M:test" *command-line-args*)` in the bb.edn and it worked, I think this is a nice addition because tests are really big and take some time to run. 
Side question, is it possible to have the repl running and test it inside? if I make some change I can reload the repl and test it again.

**Comment by lispyclouds** [comment]
Great point. Feel feel to send some PR(s) over.

> is it possible to have the repl running and test it inside?

It think the biggest challenge there is that we have pretty much all of our tests are sort of intergation tests, meaning it needs at least the db, queue or some other thing to run and its all stateful. There is some setup-teardown patterns in use but would be glad to have some more ideas!

**Comment by lispyclouds** [comment]
completed on #124
