### ISSUE TITLE
Ability to pause a pipeline

### ISSUE THREAD

**Issue by lispyclouds** [bob-cd/bob#26]
Think about the state management as the nodes won't have the pipeline in
question executing with them.

**Comment by amexboy** [comment]
@lispyclouds I'm thinking about taking this one next

Will this work? https://docs.docker.com/engine/reference/commandline/pause/

**Comment by lispyclouds** [comment]
yes exactly. this is the corresponding docker client function: https://github.com/lispyclouds/clj-docker-client#pausing-a-container

this needs you to get a bit familiar with the execution process, see https://bob-cd.github.io/bob/architecture#the-execution-model

to get this to work you need to do the following:
- check if the pipline status is actually `running`.
- find the last_pid of the pipeline from https://github.com/bob-cd/bob/blob/master/resources/migrations/003-runs.edn#L20
- this is the id of the last container that corresponds to the latest step being executed.
- pause this container using above function.
- set the status to paused.
- introduce a new status called :paused here: https://github.com/bob-cd/bob/blob/master/src/bob/api/schemas.clj#L45
- do the opposite using the unpause function and the rest.

its a bit complicated, lemme know if you need any help. will find time for it

**Comment by amexboy** [comment]
@lispyclouds 

The thing I did not figure out yet is how to continue build that was started on another node. If the unpause request reached a different node of bob, we don't have a container to continue, right?

**Comment by lispyclouds** [comment]
Lets park this issue for now and think about it. Maybe you can try #10 ?

**Comment by lispyclouds** [comment]
Closed by https://github.com/bob-cd/bob/commit/7f089a191c728942ef3261f31994f4d9d0ab31bb
