### ISSUE TITLE
Health check for external systems

### ISSUE THREAD

**Issue by lispyclouds** [bob-cd/bob#55]
- Add health checks for registered resource providers and artifact stores
- Maybe do an automatic heartbeat at an interval to all subsystems and log for failure?

**Comment by TimoKramer** [comment]
in progress

**Comment by TimoKramer** [comment]
Hey, I did the checks on external systems and artifact-stores. What would be a sensible approach to regularly check them? Any idea about a timer/scheduler?

**Comment by lispyclouds** [comment]
exactly. we can use something like https://github.com/jarohen/chime to send out
an heartbat every certain interval.

**Comment by TimoKramer** [comment]
and what should happen if the health-checks fail? only logging?

**Comment by lispyclouds** [comment]
Yeah lets just log it for now, as it will fail appropriately at runtime if
somethings wrong.

**Comment by TimoKramer** [comment]
I am currently not mixing the heartbeats for artifacts and resources with the essential checks for db and docker. what do you think? 
Should I start the heartbeats with a state?

**Comment by lispyclouds** [comment]
the external checks and essential checks should happen when a request is made on `/can-we-build-it` provided there is some external things registered.

yes, starting the cron on a mount state would be a nice way to go
