### ISSUE TITLE
Rethink Bob core

### ISSUE THREAD

**Issue by lispyclouds** [bob-cd/bob#70]
Check out Vert.x as a transport
When clj-docker-cleint is async, go for it
Check out async adapters for HugSQL

**Comment by lispyclouds** [comment]
First draft of the new proposed architechture:
![neobob2](https://user-images.githubusercontent.com/5615588/78924909-db3d4780-7a9a-11ea-8f99-4591350547dd.png)

**Comment by lispyclouds** [comment]
Considerations:
- Use of RabbitMQ as the durable queue
- Cluster to perform CRUD ops for pipelines, artifact stores and resource providers
- Cluster of pipeline runners
- Cluster of loggers
- Health check cron

**Comment by bitsapien** [comment]
What happens when a pipeline "start" follows a pipeline "create", and your CRUD Entity systems is overloaded and never persisted the "pipeline definition" ?

**Comment by lispyclouds** [comment]
In that case the general flow is:
- SInce all the services are independent, each one of them trys to _work with what is available_.
- If the start of a pipeline is requested before it exists, the runner picking it up will simply error out and put a message on the error queue.
- This error queue is to be exposed via a REST path and its upto the users discretion to decide what to do with each of the errors. Errors are quite subjective too i think.

**Comment by lispyclouds** [comment]
Being developed on this [branch](https://github.com/bob-cd/bob/tree/queue)

**Comment by lispyclouds** [comment]
The logging service is not to be used for simplicity reasons.

**Comment by lispyclouds** [comment]
Since its a distributed service architechture, consider using a schemaless DB as a value store and not postgres to avoid shared DB state issues

**Comment by lispyclouds** [comment]
![bob-db](https://user-images.githubusercontent.com/5615588/83962324-c57eaf80-a89c-11ea-8312-a877e3278903.png)
