### ISSUE TITLE
return id when starting pipeline

### ISSUE THREAD

**Issue by TimoKramer** [bob-cd/bob#71]
when starting a pipeline I have no idea which id it's got to query its status etc. It would be preferrable to return the id in the json-response.
`curl -X POST "http://localhost:7777/api/pipelines/start/groups/dev/names/test1"`
should return something like this:
```
{
  "message": "Ok",
  "id": 42
}
```
currently returns:
```
{
  "message": "Ok"
}
```

**Comment by lispyclouds** [comment]
Sounds reasonable. Maybe call it `run`?

**Comment by bitsapien** [comment]
Looking at this from a usability standpoint, the `run-id` becomes extremely important once you want to know the status of the run or even it's logs.

Post a short discussion with @lispyclouds we arrived at 3 possible solutions:

1. Implement tags/selectors like AWS/Kube and generate ids, and let the user do the guess work if they have to access a certain run. Let's assume we can get all the runs for a given pipeline(I would not know whether this is currently possible).
```sh
$ http POST http://localhost:7777/pipelines/start/groups/dev/names/pipeline1
{
  "message": "Ok"
}
$ http GET http://localhost:7777/pipelines/runs/groups/dev/names/pipeline1
{
  "pipeline": {
    "name": "pipeline1",
    "runs": [
      {
        "id": "r-0ef66ba9-e397-461b-a6d9-f52f91889264",
        "startTime": "2020-10-21T01:36:11Z"
      },
      {
        "id": "r-9264ba9-e397-461b-461b-f52f91889ba9",
        "startTime": "2020-10-22T04:39:41Z"
      }
    ]
}
$ # User looks for the time they started a run, does some guess work and identifies the correct run-id
$ http http://localhost:7777/pipelines/status/runs/r-0ef66ba9-e397-461b-a6d9-f52f91889264
{
  "status": "running"
}
```
2. Generate resource IDs upfront in the API server and pass it on to the downstream systems that picks it up. This will double up as a trace id.
```sh
$ http POST http://localhost:7777/pipelines/start/groups/dev/names/pipeline1
{
  "message": "Ok",
  "run=id": "r-0ef66ba9-e397-461b-a6d9-f52f91889264"
}

$ http http://localhost:7777/pipelines/status/runs/r-0ef66ba9-e397-461b-a6d9-f52f91889264
{
  "status": "running"
}
```
3. Specific API just for runs
```sh
$ http POST http://localhost:7778/pipelines/start/groups/dev/names/pipeline1
{
  "message": "Ok",
  "run=id": "r-0ef66ba9-e397-461b-a6d9-f52f91889264"
}

$ http http://localhost:7778/pipelines/status/runs/r-0ef66ba9-e397-461b-a6d9-f52f91889264
{
  "status": "running"
}
```

**Comment by lispyclouds** [comment]
Thanks a lot @bitsapien !

Some observations from me:

> Implement tags/selectors like AWS/Kube and generate ids, and let the user do the guess work if they have to access a certain run. Let's assume we can get all the runs for a given pipeline(I would not know whether this is currently possible).
This should be possible as each run [entry](https://github.com/bob-cd/bob/blob/main/runner/Db.md#run) in the db carries the group and name of the pipeline and one can do a join datalog query to construct the result you said. But here we need to implement the start time of the run. One suggestion here, for starters, would be to return the status instead along with the id as its also there in the run info. **This is also acting up as the run API too, like the second suggestion.** Without the need for selectors, tags etc.

> Generate resource IDs upfront in the API server and pass it on to the downstream systems that picks it up. This will double up as a trace id.
This in general would be nice but I'm thinking that would generating a run id mean its guaranteed to be picked up? Bob's current design can't really guarantee that now. Having the id geenrated internally was the guarantee its picked up. I was thinking we could implement some queue metrics like msg picked up, waiting in queue for long etc to figure out if there is an issue. In general passing an ID up front in an eventual system just seems setting expectations to the system which it may not be able to cope up with. Thoughts?

> Specific API just for runs
This we can keep if all fails I'd say. Should be easy enough to implement too.

Overall my recommendation would be the first one for now. Specially in terms of impl effort. We can iterate to better things if there's issues.

**Comment by lispyclouds** [comment]
A sample datatalog join in Crux to get the a pipeline by group and name and its assocciated id and status:
```edn
{:find  [(eql/project pipeline [:group :name]) (eql/project run [:run-id :status])]
 :where [[pipeline :type :pipeline]
        [pipeline :group "dev"]
        [pipeline :name "pipeline1"]
        [run :type :pipeline-run]
        [run :group "dev"]
        [run :name "pipeline1"]]}
```
I will test this out and report back.

**Comment by lispyclouds** [comment]
In essence im thinking a request like
```bash
$ http GET http://localhost:7777/pipelines/runs/groups/dev/names/pipeline1
```
should produce
```json
{
  "message": {
   "group": "dev",
    "name": "pipeline1",
    "runs": [
      {
        "run-id": "r-0ef66ba9-e397-461b-a6d9-f52f91889264",
        "status": "running"
      },
      {
        "run-id": "r-9264ba9-e397-461b-461b-f52f91889ba9",
        "status": "failed"
      }
    ]
}
```

What say?

**Comment by lispyclouds** [comment]
This should also help in the GUI/CLIs to list historical data too.

**Comment by TimoKramer** [comment]
I like the idea of a 'trace ID' that is generated on the apiserver. A system promising eventual consistency should not loose messages anyway. So it should be able to answer the question on what happened to a received message. Querying for that 'trace ID' would always result in something like running/aborted/completed/waiting/failed or even lost.

Consider a GUI where you click run but then you will be redirected to a site where several jobs are running and you as a user have to figure out which job is yours. Same for a CLI. From a UX perspective having an ID returned is worth considering. I see it means having another ID or changing the creation of the existing ID.

**Comment by lispyclouds** [comment]
Fair points. I think we should go ahead with generating the `run-id` from the API server and specially because this is the only thing that connects and traces through the whole of a build.

**Comment by TimoKramer** [comment]
One could just pass an id with the message into the queue, right? no need to write to the db from the apiserver, correct?

**Comment by lispyclouds** [comment]
Yes that's what I meant too, the only things writing to the DB are the runners and entities. The runner will pick up the id and the start payload can be:
```json
{
  "group": "dev",
  "name": "test",
  "run-id": "r-9264ba9-e397-461b-461b-f52f91889ba9"
}
```

**Comment by lispyclouds** [comment]
Closed by https://github.com/bob-cd/bob/commit/8d2260048847c08abf7067fd2dfe95372a415f03
