### ISSUE TITLE
Filtering for non existing groups and names fails with 404

### ISSUE THREAD

**Issue by TimoKramer** [bob-cd/bob#92]
Given there is no pipeline group named foo.

`http "http://127.0.0.1:7777/pipelines&group=foo"` should return an empty map

Actually it returns 404.

Same for status and name obviously.

**Comment by lispyclouds** [comment]
This should give a `200` HTTP status with a response:
```json
{
    "message": []
}
```
This is as expected right? I dont think it should give 404 with the currently written code. Or do you _want_ a 404 as return?

**Comment by TimoKramer** [comment]
strange :thinking: ... I have to check again on my notebook.

**Comment by TimoKramer** [comment]
obviously I am using a wrong url here. the first delimiter for the query-params should be a `?`:)

**Comment by lispyclouds** [comment]
Ahh yes! I shouldve noticed it!
