### ISSUE TITLE
Add run ids to response for /pipelines query

### ISSUE THREAD

**Issue by emgrasmeder** [bob-cd/bob#93]
Currently the only way to get a run id is to record it after kicking off a job. 

There's already a [query to get the list of pipelines](https://bob-cd.github.io/pages/api-reference.html#operation/PipelineList), my idea is the put the run ids into that response. 

This is what a response from `/pipelines` _currently_ looks like:
```
{
  "group": "dev",
  "image": "golang:1.15-alpine",
  "name": "pipeline2",
  "resources": [...],
  "steps": [...]
}
```
My proposal is to add another top layer key called something like "runs" with a list of run ids and run statuses. 
So the new response from `/pipelines` would look like this:
```
{
  "group": "dev",
  "image": "golang:1.15-alpine",
  "name": "pipeline2",
  "resources": [...],
  "steps": [...],
  "runs": [
    {"run-id": "r-0ef66ba9-e397-461b-a6d9-f52f91889264", "status": "running"},
    {"run-id": "r-abcdef", "status": "failed"}
  ] 
}
```

Happy for more feedback or ideas.

**Comment by emgrasmeder** [comment]
I suppose the possible status values would be one of 
- done
- failed
- running
- (can you think of anything else?)

**Comment by emgrasmeder** [comment]
We could also add a dedicated path to query with a GET at `/pipelines/group/dev/names/test/runs`

**Comment by lispyclouds** [comment]
@emgrasmeder can this be closed with the new endpoint?
