### ISSUE TITLE
Figure out necessary java modules

### ISSUE THREAD

**Issue by lispyclouds** [bob-cd/bob#97]
So that all of the services can have a purpose built JVM via [jlink](https://docs.oracle.com/javase/9/tools/jlink.htm#JSWOR-GUID-CECAC52B-CFEE-46CB-8166-F17A8E9280E9) and small docker images

**Comment by zerg000000** [comment]
For a quick win, you might consider [jib](https://github.com/GoogleContainerTools/jib) and [distroless](https://github.com/GoogleContainerTools/distroless)?

**Comment by zerg000000** [comment]
If you aim high, GraalVM native-image would be more interesting?

**Comment by lispyclouds** [comment]
Hey @zerg000000 👋🏽 

Thanks a lot for the suggestions! I have indeed looked at distroless but not jib yet. Since jlink produces a custom JVM for Bob's needs I'm thinking with jlink+alpine would it be a smaller image than with distroless as I understand it would still pack all the modules? I'm not sure, hence didnt really give this more time now. However I would love to see if it indeed does and that would be nice as we have to do much less of an effort. 😄 

Having said that, if you would like to raise some PRs for this, they would be swiftly addressed! I would like to find more time to think this over and if you want to take this up its much much appreciated! 🙏🏽 

I think a native image would not be so suited for the following reasons:
- This is a long running app and would benefit from the JVM's JIT, which is not present when we AOT compile it. Native images are more suitable for fast startup and quickly finishing apps.
- We pull in a fair amount of deps here and making sure all are Graal compatible is non-trivial.
